import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Better.com Clone | Balaskanthan",
  description: "A replica of Better.com built with Next.js and Tailwind CSS. Includes Home, About Us, Mortgage Calculator, and Start pages.",
  keywords: "Better.com, Next.js, Tailwind CSS, Mortgage Calculator, Clone Website, Balaskanthan",
  authors: [{ name: "Balaskanthan" }],
  openGraph: {
    title: "Better.com Clone | Balaskanthan",
    description: "Fully responsive clone of Better.com with Home, About, Mortgage Calculator, and Start pages. Built using Next.js & Tailwind CSS.",
    url: "https://better-com-clone-balas.vercel.app",
    siteName: "Better.com Clone",
    type: "website",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
